apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mypod2s10
  name: mypod2s10
spec:
  ports:
  - name: "80"
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    run: piyush2
  type: NodePort
status:
  loadBalancer: {}
