apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: piyush20
  name: piyush20
spec:
  containers:
  - image: nginx
    name: piyush20
    ports:
    - containerPort: 81
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
