apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: piyush2
  name: piyush2
spec:
  containers:
  - image: nginx
    name: piyush2
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
