apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  volumes:
  - name: piyushvol
    configMap:
     name: piyushweb
  containers:
  - image: nginx
    name: pod1
    volumeMounts:
    - name: piyushvol
      mountPath: /usr/share/nginx/html/
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
